apiVersion: apps/v1
kind: Deployment
metadata:
  name: libraryservicedeployment
spec:
  selector:
    matchLabels:
      app: libraryservice
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: libraryservice
    spec:
      containers:
      - image: {{ .Values.deployment.containers.image }}
        name: {{ .Values.deployment.containers.name }}
        imagePullPolicy: Always
        ports:
        - containerPort: {{ .Values.deployment.containers.ports.containerPort }}
              
        env:
          - name: {{ .Values.deployment.containers.env.name }}
            valueFrom:
              configMapKeyRef:
                name: librarycm
                key: bookinventory.endpoint
                
      restartPolicy: Always
